# Generated by Django 3.2.18 on 2023-04-06 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
