# Generated by Django 3.2.18 on 2023-04-10 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alldata_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='alldata',
        ),
        migrations.DeleteModel(
            name='signup',
        ),
    ]
