# Generated by Django 3.2.18 on 2023-04-20 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alldata_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='alldata',
            name='links',
            field=models.CharField(default=django.utils.timezone.now, max_length=100000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alldata',
            name='date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='time',
            field=models.CharField(max_length=255),
        ),
    ]
